name: check

on: [pull_request, push]

jobs:
  mix_check:
    name: mix check (Elixir 1.20.2, OTP 29.0.4)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.20.2'
          otp-version: '29.0.4'

      - name: Cache deps and build
        uses: actions/cache@v5
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-29.0.4-1.20.2-${{ hashFiles('**/mix.lock') }}-git-${{ github.sha }}
          restore-keys: |
            deps-${{ runner.os }}-29.0.4-1.20.2-${{ hashFiles('**/mix.lock') }}
            deps-${{ runner.os }}-29.0.4-1.20.2

      - name: Fetch deps
        run: mix deps.get

      - name: Remove application build
        run: mix clean

      - name: Compile deps
        run: mix deps.compile

      - name: Compile app
        run: mix compile

      - name: Run check
        run: mix check
